Feat/ab 117 create admin and doctors
HospiCloud-Team/hospicloud-frontend pull request #19
Opened 2021-11-21 21:37 UTC by kelvinlee0225

- [x] add "create admin user" by an admin
- [x] add "create doctor user" by an admin

2021-11-24 01:48 UTC, cesarlopezt requested changes

2021-11-24 01:48 UTC, cesarlopezt commented on src/api/users/index.ts
> +import { IDoctorRegister } from "../../models/IDoctor";
El estándar que estamos usando es INewDoctor y así, si te fijas en otras interfaces

2021-11-24 01:48 UTC, cesarlopezt commented on src/pages/DashboardAdmin/components/AddAdminPersonnel.tsx
> +import ArrowLeft from "../../../resources/ArrowLeft.svg";
No está mal, pero si quieres puedes usar bootstrap icons y así no tienes que guardar un svg ni hacerle import

2021-11-24 01:48 UTC, cesarlopezt commented on src/pages/DashboardAdmin/components/AddAdminPersonnel.tsx
> +                handleShow={updateModal}
Cómo es tan modificable este modal puedes ponerlo en src/components y así lo reusamos

2021-11-24 01:48 UTC, cesarlopezt commented on src/pages/DashboardAdmin/components/AddDoctorPersonnel.tsx
> +  // };
Necesitamos este código comentado?

2021-11-24 01:48 UTC, cesarlopezt commented on src/pages/DashboardAdmin/components/AddDoctorPersonnel.tsx
> +    let specialties = hospitalSpecialties.data.map((item) => {
Puede ser un const y trata de no usar el mismo nombre que usas para el state

2021-11-24 01:48 UTC, cesarlopezt commented on src/pages/DashboardAdmin/components/AddDoctorPersonnel.tsx
> +                    )}
Remueve el código comentado

2021-11-24 01:48 UTC, cesarlopezt commented on src/pages/RegisterHospitalAndAdmin/RegisterAdminPage/dist/index.js
> +    var _a = react_1.useState(false), isShowModal = _a[0], setIsShowModal = _a[1];
Que carajo es eso

2021-11-24 01:48 UTC, cesarlopezt commented on src/pages/RegisterHospitalAndAdmin/RegisterAdminPage/dist/index.js
> +exports["default"] = RegisterAdmin;
Mi bro, eso ta compilado, descompila eso

2021-11-24 01:48 UTC, cesarlopezt commented on src/router/dist/index.js
> +exports["default"] = Routes;
Más código compilado

2021-11-24 02:53 UTC, kelvinlee0225 commented on src/pages/DashboardAdmin/components/AddAdminPersonnel.tsx
> +import ArrowLeft from "../../../resources/ArrowLeft.svg";
Tengo entendido que se complica al querer ajustar su tamaño, por ende, lo descargué y lo ajusté con styled component

2021-11-24 06:22 UTC, cesarlopezt reviewed
Me parece bien todo. Revisa que todo siga funcionando y si react-select no se está usando vamos a quitarlo.

Luego de eso me avisas para darle approve

2021-11-24 06:22 UTC, cesarlopezt commented on package.json
> +    "react-select": "^5.2.1",
Creo que ya no estamos usando esta dependencia

2021-11-24 06:22 UTC, cesarlopezt commented on src/pages/DashboardAdmin/components/AddAdminPersonnel.tsx
> +      // This would be a GET call to an endpoint
Un get a cual endpoint?

2021-11-26 03:35 UTC, kelvinlee0225 commented on src/pages/DashboardAdmin/components/AddAdminPersonnel.tsx
> +      // This would be a GET call to an endpoint
Realmente, no sé por qué puse eso XDDD, por eso lo borré hahahha

2021-11-26 04:04 UTC, cesarlopezt approved these changes

2021-11-26 04:07 UTC, merged